### ISSUE TITLE
Field names are wrong when a ChoiceField

### ISSUE THREAD

**Issue by richardcornish** [rafaponieman/django-jquery-form-validation#1]
I don't know if this project is still being maintained, but I don't think `forms.ChoiceField` gets the correct name.

The current code checks against a few different types, but not `forms.ChoiceField`. As it stands, Django makes those HTML widgets like `<input type="radio" id="id_[model_field]-[form_field]_1" value="True" name="[model_field]-[form_field]" required="required">`.

The template tag currently interprets the choice field with just a name, so `{% validation_rules form %}` ends up looking like `{"[form_field]": {"required": true}}` which doesn't correspond to the HTML widgets that Django makes. It would need to be `{"[model_field]-[form_field]": {"required": true}}`

My guess would be to add another check like `if(isinstance(form.fields[field_name], forms.ChoiceField)):` but I wouldn't know where to go from there.

**Comment by rafaponieman** [comment]
Hi Richard, I'll take a look into it. It started as something I needed for a project, but it seems a few people are using it.

Thanks for your report!
